blueprint:
  name: Rotate & Backup HVAC Controller
  description: >
    Daily rotate between two HVAC entities and keep room temperature
    between a target range. If it gets too hot, kick in the backup HVAC
    until it cools down.
  domain: automation
  input:
    primary_climate:
      name: Primary HVAC
      selector:
        entity:
          domain: climate
    backup_climate:
      name: Backup HVAC
      selector:
        entity:
          domain: climate
    temperature_sensor:
      name: Room Temperature Sensor
      selector:
        entity:
          domain: sensor
    rotation_helper:
      name: Rotation Helper (Input Boolean)
      description: >
        Create an input_boolean beforehand; it will toggle daily to
        decide which HVAC is “primary” that day.
      selector:
        entity:
          domain: input_boolean
    rotate_time:
      name: Daily rotation time
      default: "00:00:00"
      selector:
        time: {}
    target_temp:
      name: Target (mid‑point) temperature
      default: 21
      selector:
        number:
          unit_of_measurement: "°C"
          min: 5
          max: 30
          step: 0.5
    high_temp:
      name: High threshold
      default: 23
      selector:
        number:
          unit_of_measurement: "°C"
          min: 5
          max: 40
          step: 0.5
    low_temp:
      name: Low threshold
      default: 20
      selector:
        number:
          unit_of_measurement: "°C"
          min: 5
          max: 30
          step: 0.5

trigger:
  - platform: time
    at: !input rotate_time
    id: rotate
  - platform: numeric_state
    entity_id: !input temperature_sensor
    above: !input high_temp
    id: temp_high
  - platform: numeric_state
    entity_id: !input temperature_sensor
    below: !input low_temp
    id: temp_low

action:
  # 1) Rotation at the specified time
  - choose:
      - conditions:
          - condition: trigger
            id: rotate
        sequence:
          # flip the helper
          - service: input_boolean.toggle
            target:
              entity_id: !input rotation_helper

          # re-calc who is primary/backup _after_ toggle
          - variables:
              rotation_flag: !input rotation_helper
              primary_entity: !input primary_climate
              backup_entity: !input backup_climate
              primary_today: >
                {% if is_state(rotation_flag, 'on') %}
                  {{ backup_entity }}
                {% else %}
                  {{ primary_entity }}
                {% endif %}
              backup_today: >
                {% if is_state(rotation_flag, 'on') %}
                  {{ primary_entity }}
                {% else %}
                  {{ backup_entity }}
                {% endif %}

          # set the new primary to COOL @ target_temp
          - service: climate.set_hvac_mode
            target:
              entity_id: "{{ primary_today }}"
            data:
              hvac_mode: cool

          - service: climate.set_temperature
            target:
              entity_id: "{{ primary_today }}"
            data:
              temperature: !input target_temp

          # ensure the other unit is OFF
          - service: climate.set_hvac_mode
            target:
              entity_id: "{{ backup_today }}"
            data:
              hvac_mode: 'off'

  # 2) For any temperature trigger, recalc primary/backup
  - variables:
      rotation_flag: !input rotation_helper
      primary_entity: !input primary_climate
      backup_entity: !input backup_climate
      primary_today: >
        {% if is_state(rotation_flag, 'on') %}
          {{ backup_entity }}
        {% else %}
          {{ primary_entity }}
        {% endif %}
      backup_today: >
        {% if is_state(rotation_flag, 'on') %}
          {{ primary_entity }}
        {% else %}
          {{ backup_entity }}
        {% endif %}

  # 3) Too hot → turn on backup
  - choose:
      - conditions:
          - condition: trigger
            id: temp_high
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: "{{ backup_today }}"
            data:
              hvac_mode: cool
          - service: climate.set_temperature
            target:
              entity_id: "{{ backup_today }}"
            data:
              temperature: !input low_temp

  # 4) Cooled → turn off backup
  - choose:
      - conditions:
          - condition: trigger
            id: temp_low
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: "{{ backup_today }}"
            data:
              hvac_mode: 'off'
